# Generated by Django 5.2.5 on 2025-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_enrollment_score_user_profile_picture_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='record_type',
            field=models.CharField(choices=[('achievement', 'Achievement'), ('certification', 'Certification')], default='achievement', max_length=20),
        ),
    ]
